# Generated by Django 6.1.1 on 2026-10-02 12:04

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountORM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Account number must contain exactly 10 digits.', regex='\\A[0-9]{10}\\Z')], verbose_name='Account number')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Balance')),
            ],
        ),
    ]
