# Generated by Django 6.1.1 on 2026-10-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountorm',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='clients.clientsorm'),
        ),
        migrations.AddConstraint(
            model_name='accountorm',
            constraint=models.CheckConstraint(condition=models.Q(('account_number__regex', '^[0-9]{10}$')), name='account_number_10_digits'),
        ),
        migrations.AddConstraint(
            model_name='accountorm',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='account_balance_non_negative'),
        ),
    ]
