# Generated by Django 6.1.1 on 2026-10-02 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionORM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESS', 'Process'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.accountorm')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='accounts.accountorm')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntriesORM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('category', models.CharField(choices=[('welcome_bonus', 'Welcome Bonus'), ('transfer', 'Transfer'), ('fee', 'Fee')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounts.accountorm')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='transactions.transactionorm')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.AddConstraint(
            model_name='transactionorm',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transactionorm',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='transaction_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactionorm',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='transaction_different_accounts'),
        ),
        migrations.AddConstraint(
            model_name='transactionorm',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESS', 'SUCCESS', 'FAILED', 'CANCELED'])), name='transaction_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentriesorm',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ledger_amount_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentriesorm',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['welcome_bonus', 'transfer', 'fee'])), name='ledger_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentriesorm',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'welcome_bonus')), fields=('account',), name='ledger_one_welcome_bonus_per_account'),
        ),
    ]
